### ISSUE TITLE
steps running very slowly

### ISSUE THREAD

**Issue by dustin-graham** [domesticmouse/vscode-typer#2]
Hi Brett, Loved your talk at Google I/O and was so impressed with the auto-type plugin you used in VSCode. I'm giving a presentation tomorrow at the Phoenix Flutter & Dart meetup and I'm hoping to use your plugin to step through the code as you did on stage. I've written some bash scripts to run through my git history and output numbered snapshots of my project files and I've plugged them into a "typer/steps.json" file. I reloaded the plugin and it does work. However, it runs painfully slow between steps. I let it have the default 5 chars per change and it does 5 characters every 2 seconds or so. I'm looking at the code and it looks like the heartbeat setting is at 33ms which should look great. But for some reason this just runs sluggishly. I'm suspecting that each "heartbeat()" is taking longer than expected. I'm normally an IntelliJ person, and so I'm unfamiliar with VSCode. Are there settings I should tweak to make this run as it did for you on stage?

**Comment by domesticmouse** [comment]
The issue here is that the heartbeat is running a full JSDiff, and if your code is sufficiently complex, then the time requirements of the diff can explode in complexity.

You will also notice that I try to always add large code blocks only at the end, as this reduces the number of available choices for JSDiff. It can handle making small patches in the middle of the codebase, but full rewrites bring it to its knees.

You can try bringing up the number of characters to patch at each heartbeat, I bring it up to 100 characters in those cases. But I also find in places where JSDiff is having issues that people following the code will also have problems parsing what is going on.

So, really, the best answer is to simplify the heck out of your code.

**Comment by dustin-graham** [comment]
@domesticmouse Thanks a lot for the tip. I did a few smaller revisions and did find that it sped right up. The revision that it choked on was me removing all the standard comments in main.dart from a starter project. it didn't like removing comments at all. Incidentally, cranking up the charsPerChange didn't seem to help. I put it up to 10,000 just for giggles and I didn't notice a difference.

**Comment by dustin-graham** [comment]
@domesticmouse This is unrelated, but did you use any automation scripts to build your your steps as I'm doing? I'm generating revisions from my git commits, but I've still got to go assemble them in the json file by hand which is a bit burdensome.

**Comment by domesticmouse** [comment]
Yeah, it's not that smart. Amusingly, you will find it gets better if you reduce the amount of work it has to do, so instead of stripping all the comments, just do a single comment block at a time. You really need to manage the complexity of the available choices. On the upside, this tends to force you to make only localized changes, which improves the story telling.

So, yeah, known flaw that I'm not in a rush to fix.

**Comment by domesticmouse** [comment]
As to automation, nope. I think very carefully about the story I am telling at each point, and the code that I am introducing at each change. It takes about a week of my time to get a single talks worth of code smooth enough to present.

**Comment by dustin-graham** [comment]
@domesticmouse cool, good to know. My plan is to use git commits to bookmark the storytelling and then generate the steps for each file in the project and generate numbered snapshots. I'll leave the steps.json as a manual exercise then. Thanks!

**Comment by domesticmouse** [comment]
I hope it all went well =)
